### ISSUE TITLE
Lost items after Roll

### ISSUE THREAD

**Issue by dikano** [Anonomit/LootReserve#18]
**Describe the bug**

hey guys this is the second time this happen on WOTLK i believe the first time LootReserve was on another version current version used when bug happended is 2023-01-28
people res on an item after the boss gets down i use the roll feature the we see the rolls Lootreserve announces who won then the item disapears goes to no one.
i had this happen on phase one OS2D 25m man
it happened again today on EOE25m 
the person who one today was me and i was sitting on the loot box i have free bag slots ect
on the loot chat there is no mention of who got the item it just gets deleted
**To Reproduce**

no idea how to reproduce

**Expected behavior**
A loot gets deleted after the roll feature has been used

**Screenshots**
![loot gone thanks shitty addon](https://user-images.githubusercontent.com/35535890/216735773-9d4c1fc7-8765-4100-ab54-cb89939038ed.PNG)

**Version:**
- WoW Version 2.4.1 47720
 - Addon Version  2023-01-28

**Comment by Anonomit** [comment]
LootReserve isn't deleting items. There's a function to do that, and LootReserve never uses it. It's also a protected function, which means it would require a hardware event (you'd need to click a confirm button or something) on a secure frame (LootReserve doesn't use any of those).

One of two things is probably happening. Either the item is being automatically master looted to the winner (if you have that setting enabled) and escapes notice, or it's a Blizzard bug where the master looter can't loot a unique item when it's the last thing on a corpse. I think you might be able to reproduce this by leaving the unique obsidian sanctum backpack on the boss and looting the rest of the items. If the master looter already owns the bag and stops looting the corpse, they might not be able to click the corpse again. I don't know if that bug is still in the game, but I would suggest you don't close loot windows until they're empty.
