### ISSUE TITLE
Items with suffixes don't show them in the reserve list.

### ISSUE THREAD

**Issue by Cabro** [Anonomit/LootReserve#26]
**Describe the bug**
Followup to the previous bug.
Now you can reserve the items, but you don't see the suffixes in the "My reserves" and "All reserves" tabs. They show the basic nonsuffixed item.

**To Reproduce**
1. Reserve an item from To4W
2. Click on "My reserves"
3. See items without suffix

**Expected behavior**
It would be difficult as the master looter to distinguish between multiple suffixes of the same item when they have been reserved by multiple people.

**Screenshots**
![image](https://github.com/Anonomit/LootReserve/assets/1155017/650b6656-34fe-41d4-8065-43c944b8cac7)

**Version:**
- WoW Cata
 - Addon Version [e.g. 2024-06-02]

**Additional context**
I know the items all have the same ID, but there has to be a way to show the exact suffix that has been reserved. For example, mage, warlock and priest all have in their bis lists Planetary Amulet, but warlocks have "of the Flameblaze", mages have "of the Wildfire" and priests have "of the Undertow". I can see this being a source of confusion.

**Comment by Anonomit** [comment]
This is intentional. Reserves are done by item ID, which means you are reserving every suffix at once. Though it would be possible to isolate reserves to only specific suffixes, this isn't how they're being handled in any Soft Reserve tool that I'm aware of.

The thinking is that this is probably a situation where it's better to let players overlap their reserves and then self-correct depending on which suffix actually does end up dropping - same as how it was done back in Karazhan in TBC.

Both ways of doing reserves have complications. With the way it is now, groups will need to figure out internally whether they'll be giving priests priority on "of the Undertow" items. But other groups won't like being able to reserve only a single suffix, and many suboptimal drops can be reforged into near-bis stats.

If you want an option to reserve individual suffixes, the best place to open a discussion would be on [the Softres.it discord](https://discord.gg/PkX5eVm). I don't currently plan on adding this feature, but if there's enough demand for it then perhaps it could happen.
