### ISSUE TITLE
Tooltip window are not clamp to screen

### ISSUE THREAD

**Issue by Cabro** [Anonomit/LootReserve#27]
**Describe the bug**
When you have too many roll options, the tooltip becomes too wide for the screen and the popup frame is outside of the actual screen.

**To Reproduce**
1. Go to Lootreserve HOST, the dice option menu, "Roll For:" -> "Add..."
2. Add many many roll options.
3. The tooltip frame becomes so wide that the child frame goes completely off screen.

**Expected behavior**
The child frame should be clamped to screen. Because reasons.

**Screenshots**
![image](https://github.com/Anonomit/LootReserve/assets/1155017/d6eb015c-a6c7-4a9e-aa7e-0d88df4fd382)
**Version:**
- WoW cata
 - Addon 2024-06-04

**Additional context**
I only added this many roll options because there is no option when creating a new roll option for the actual roll limit and i wanted to reach /roll 50.

**Comment by Anonomit** [comment]
The dropdown menu is using a library which uses default Blizzard dropdown menu functionality. Blizzard doesn't appear to offer any way to limit the maximum width (only the minimum). Doing so myself would probably cause taint issues.

Instead, I'll limit the number of displayed stages in the first menu. Stage names are already capped at 50 characters, so this should prevent the menu from growing too wide due to a large number of stages.

**Comment by Cabro** [comment]
I was only referring to the child popup window, that can be seen on the left side of the screen cut in half. I know there is a way to keep frames on screen, that's what I am suggesting.

**Comment by Anonomit** [comment]
There's just not enough pixels for how wide your dropdown menu got. Hopefully it won't get that wide anymore though, even with a lot of stages.
