### ISSUE TITLE
There is no option to define the roll limits for a custom roll rule.

### ISSUE THREAD

**Issue by Cabro** [Anonomit/LootReserve#28]
**Describe the bug**
There is no option to set the roll limit for a custom roll rule. They only go down by 1.

**To Reproduce**
1. Go to Lootreserve Host
2. Click on dice menu, scroll to "Roll For:" -> "Add..."

**Expected behavior**
You can enter the name, but there is no option to select the actual limit for the roll. Or stage, as it's named here. It only goes down by 1. I should have the option to manually select a limit, say 50 for example.

**Screenshots**
![image](https://github.com/Anonomit/LootReserve/assets/1155017/a3082506-bf49-4d31-ab3e-30e834ab2f79)

**Version:**
- WoW cata
 - Addon 2024-06-04

**Additional context**

**Comment by Anonomit** [comment]
I think you may be misunderstanding the function of tiered rolls. Rolls with higher maximums always win over rolls with lower maximums. This is by design, and is indicated on the tooltip for the Tiered Rolls toggle. If a 1-100 roll exists, then there's no difference between a 1-99 and a 1-50 roll; they're both irrelevant because the 1-100 roll will win.

If you're trying to compare rolls with different maximums, then you should disable tiered rolls. It sounds like you might be setting up some kind of "roll penalty" for some players by having them roll with a handicap. There's a setting in the Host window to allow all roll formats. If you turn this on, then the addon will allow people to roll with any maximum they want, and all the rolls will be considered to find the winner (still only one roll per player allowed).

If this doesn't work for your use case, then please let me know more details about what kind of loot system you're running.

**Comment by Cabro** [comment]
I understand how the priority of rolls is. I'm just saying there is no way to add a specific roll stage. This should also be a nonissue if you changed the ties to not be autocompleted, though.
