### ISSUE TITLE
Addon allows reserves of already owned Unique items

### ISSUE THREAD

**Issue by Kami-the-Kami** [Anonomit/LootReserve#3]
Issue: People with the addon can still use the GUI to reserve unique items such as [Pit Lord's Satchel]
Solution: Don't let people reserve Unique items they already own.

**Comment by Anonomit** [comment]
Since the host has no knowledge of what client owns, this can't be enforced for players without the addon. It also can't be enforced for imported reserves. The host's definition of a "usable item" is looser than the client's, but it's the only definition that can be verified by everyone.

13025d85cbd2ee44b504e33b663b45b86f464556 will cause the GUI to show red text on items which the client does not consider usable. There is also an option in the client window to hide the roll popup on unusable items. Both these cases will use client calculation to determine if the item can be used. The host will continue to be the single source of truth for this decision when it comes to reserves, and will not restrict reserves on items that it cannot verify are unusable. Players can still reserve and roll on items that the host determines are usable for that player even if the client disagrees, though there should be no benefit for the player to resist the client's suggestion. In many cases the item can't even be looted to the player.

When the client determines if an item is usable, it uses the same process as the host, but with some additional rules. It considers all items the player owns, which professions the player has trained, and any quests the player is on or has completed. So Head of Magtheridon will be unusable if the player already owns one, is on the quest, or has completed the quest. Pit Lord's Satchel is unusable to any player that already owns one. An engineering schematic is unusable to any player who is not an engineer.
